### ISSUE TITLE
Add generic `context` argument to `Loader::load`?

### ISSUE THREAD

**Issue by super-continent** [a1phyr/assets_manager#11]
I want to use this crate to load assets in a `ggez` project, which includes images, however, I cannot use the crates wrapped `image` types, as those aren't compatible, and I cannot write my own `Loader` implementation for `ggez::graphics::Image` because to load anything, it requires a mutable reference to a `Context`

I think [warmy](https://crates.io/crates/warmy) has a good solution for this, with a generic argument for a mutable  reference to some "context" type specified by the user. However I would like to use this crate, as warmy hasn't been updated in 2 years, and appears to no longer be maintained.

Thoughts on this change? It would require some updates to all `Loader` implementations, but I think it would provide much-needed flexibility to the user

**Comment by a1phyr** [comment]
Hello, thanks for this suggestion !

I agree that not having a context is a limitation of `assets_manager`.

I have already thought about it, but the main difficulty is its relation with hot-reloading. Currently it is done on another thread, and part (or all) of it is done on background. This would not really be compatible with a context, especially if it is `!Send + !Sync` like in `ggez`.
This could be solved by allowing hot-reloading on a "local" thread, which would also provide a better solution for #10.

In the meantime you can do something like this:
```rust
fn load_png(cache: &AssetCache, ctx: &mut ggez::Context, image_id: &str) -> Result<ggez::graphics::Image> {
    let img = cache.load::<assets::Png>(image_id)?.read().to_rgba8();
    let img = ggez::graphics::Image::from_rgba8(ctx, img.width() as u16, img.height() as u16, &img)?;
    Ok(img)
}
```

Additionally, if you care about performance and not about hot-reloading (eg for a release build), you can store a `ggez::graphics::Image` in a cache with `AssetCache::get_or_insert`.

**Comment by super-continent** [comment]
Ok, thank you for the example code! This fixes my problem for now.

**Comment by a1phyr** [comment]
You might be interested in an integration of `assets_manager` for `ggez` I have just released: https://crates.io/crates/ggez-assets_manager

It includes the code above and more !

**Comment by super-continent** [comment]
looks good, thank you!
