### ISSUE TITLE
ImageLoader example?

### ISSUE THREAD

**Issue by scambier** [a1phyr/assets_manager#12]
Hello, I'm trying to use the ImageLoader with the following code:

```rust
pub struct Image(pub Arc<DynamicImage>);

impl Image {
    pub fn to_image(&self) -> Arc<DynamicImage> {
        Arc::clone(&self.0)
    }
}

impl Asset for Image {
    const EXTENSIONS: &'static [&'static str] = &["png", "jpg"];
    type Loader = ImageLoader;
    const HOT_RELOADED: bool = true;
}

let img = cache.load::<Image>("Sprite-0001").unwrap().read();
```

But I have the following error on the line `type Loader = ImageLoader;`

the trait bound `ImageLoader: Loader<Image>` is not satisfied
the following implementations were found:
  <ImageLoader as Loader<DynamicImage>>
  <ImageLoader as Loader<assets_manager::asset::Png>>rustc[E0277](https://doc.rust-lang.org/error-index.html#E0277)

**Comment by a1phyr** [comment]
Hello !

The problem here is that `ImageLoader` does not know how to create your custom type. 

One way to fix this is to add the good implementation :

```rust
use assets_manager::loader::Loader;

impl Loader<Image> for ImageLoader {
    fn load(content: Cow<[u8]>, ext: &str) -> Result<Image, BoxedError> {
        let image = ImageLoader::load(content, ext)?;
        Ok(Image(Arc::new(image)))
    }
}
```

Even simpler, you can `impl From<DynamicImage> for Image` and use `LoadFrom<DynamicImage, ImageLoader>` as `Loader` in `Asset` impl.

**Comment by scambier** [comment]
Thank you :)
