### ISSUE TITLE
[Feature request] Watch directory for change

### ISSUE THREAD

**Issue by Shelim** [a1phyr/assets_manager#16]
There are many cases when watching directory for any change is more desired then using Compound assets. Examples includes:

 - Localization/Language files - Especially if their file names are not relevant in lookup process (like in Project Fluent)
 - User-created mods - This allows new module auto detection without restarting the application
 - Entities that can be auto-spawned without listing them - Examples includes auto-spawning enemies group in dungeon crawler that satisfy given condition, instead of being hard-wired up in given map or map generator

As of now, Directory does not support watching in Asset Manager. I wonder if this feature can be relaxed to allow at least some information (file/directory added/changed/removed) to be passed to client application from Asset Manager.

There exists some workaround (most notably using 3rd party tools like notify or filesystemwatcher), but because Asset Manager allows non-direct-file system access (like zip archives or virtual files), they essentially requires re-implementation of core features.

**Comment by a1phyr** [comment]
Yes, adding hot-reloading to directories would be very nice, though that would require some API redesign around them. I'll be happy to work on that !

Regarding hot-reloading of ZIP files, it isn't supported for the moment but it could be a nice addition too !
