### ISSUE TITLE
[Feature request] Pass source entity information to load function in Loader trait

### ISSUE THREAD

**Issue by Shelim** [a1phyr/assets_manager#17]
Right now the Loader's `load` function have following signature:

`fn load(content: std::borrow::Cow<[u8]>, _ext: &str)`

While this is sufficient for loading correct assets, it is not enough to generate meaningful error message on failure.

(By meaningful I understand the message that carry all the information for technical user to resolve given issue)

I wonder if it is possible to pass information regarding source entity, used to load given asset - for debugging purposes. As Asset Manager supports loading from zip files, standard file system and, possibly, others means, the source entity must contain all the information required to track the offending file.

For example I wish to be able to generate following information to the user:

 - "The file xyz/abc.jpg from archive content/abc.zip is corrupted and will not be loaded"

I also wish to return OK handle with placeholder jpg image, so the rest of the application can progress without stopping on wrong assets. Therefore I cannot rely on log feature of Asset Manager (as I believe errors will return incorrect assets later on)

**Comment by a1phyr** [comment]
About error formatting, I understand that you think that the asset id is not enough. However, it may not always make sense to tell a precise location as you showed: what if a `Source` takes its data from several `Source`s [like for `ggez`](https://github.com/a1phyr/ggez-assets_manager/blob/master/src/source.rs#L75) ?

Adding such information to the error should probably be the responsibility of the `Source` itself. It could easily be added to `FileSystem` and maybe to `Zip` too. In the meantime you can create a simple wrapper.

For your second need, you can use [`Asset::default_value`](https://docs.rs/assets_manager/latest/assets_manager/asset/trait.Asset.html#method.default_value) on your type to log errors and provide a placeholder value.

**Comment by a1phyr** [comment]
Implemented in ca1fcfe3a671d84ecb77e68535b4b443da5a8b61 and 6e2f35fa216ea9948f3aab78bda8785e02b07334.
