### ISSUE TITLE
Use a channel crate that supports selection to avoid waking up the hot reloader thread 50 times per second

### ISSUE THREAD

**Issue by zesterer** [a1phyr/assets_manager#2]
Waking up a thread so regularly is likely to cause problems for schedulers that don't handle multi-tasking particularly well (such as the schedulers of Windows and MacOS). Switching to a crate that permits selecting on the two channels instead of `try_recv`-ing them both in a wait loop will improve performance and also reduce reload latency.

Examples of crates that support this include `crossbeam_channel` and my own `flume`.

**Comment by a1phyr** [comment]
Yeah, this a great idea !

Unfortunatly, [`notify` currently uses `std`'s channels in its API](https://docs.rs/notify/4.0.15/notify/trait.Watcher.html#tymethod.new), so another crate's channels would be quite hard to integrate. It is easily doable with pre-releases of `notify` 5.0, but I really dislike the API, and I would prefer to pick a stable version anyway.

**Comment by a1phyr** [comment]
As a workaround, we could spawn a thread to receive from an `std` channel and output in a selectable channel, but it seems very overkill and bad for context-switching anyway. Any idea ?

**Comment by a1phyr** [comment]
Closed by 87328eb
