### ISSUE TITLE
Hot Reloading - Inconsistent Path Format Requirements

### ISSUE THREAD

**Issue by JohnEdChristensen** [a1phyr/assets_manager#21]
Calling `AssetCache::load` with a path formatted with `"/"` delimiters, rather than `"."` delimiters works when initially loading an asset. However, hot reloading silently fails for these paths. 

```rust
    let cache = AssetCache::new("assets").unwrap();
    let material_handle = cache.load::<NamedMaterials>("model/materials").unwrap();

    // Works!
    let initial_materials = material_handle.read().0;

    loop {
        cache.hot_reload();
        // Doesn't update on file change, silently fails and returns old value (no logs on asset change)
        let materials = material_handle.read().0;
        initial_materials == materials; // returns true
    }
```

It would be nice if either `AssetCache::load` was updated to reject this format, or if hot reloading was updated to support this format. It was a bit painful to figure out why hot reloading wasn't working for nested directories, when it was working fine for the initial load.

**Comment by a1phyr** [comment]
Thanks for reporting this!  I will fix it in `0.13` to avoid breaking existing code that may rely on that.
