### ISSUE TITLE
What asset types are supported?

### ISSUE THREAD

**Issue by Zireael07** [a1phyr/assets_manager#3]
Let's say I want to use a custom asset type that is similar to json but not quite, or some graphics assets...

**Comment by a1phyr** [comment]
You can use any asset format, the [`Loader`](https://docs.rs/assets_manager/0.4.0/assets_manager/loader/trait.Loader.html) trait fits this role. You can implement it to provide a conversion from raw bytes to your asset type.

If you use a generic format (such as json), you can even make a generic impl once and for all:
```rust
struct CustomFormatLoader;
impl<T> Loader<T> for CustomFormatLoader
where
    // This example uses serde but other bounds work too
    T: serde::DeserializeOwned
{
    // Actual implementation
}

// Some struct you want to load with your custom format
#[derive(Deserialize)]
struct Weapon {
    name: String,
    kind: String,
    damage: u32,
}

impl Asset for Weapon {
    const EXTENSION: &'static str = "custom";

    // `Weapon` implements `Deserialize` so `CustomFormatLoader`
    // implements `Loader<Weapon>`
    type Loader = CustomFormatLoader;
}
```

If your type implements `From<Vec<u8>>`, you can also use `LoadFrom<Vec<u8>, BytesLoader>` as `Loader` for your asset type, but it may be less efficient in some cases (if you don't actually need ownership on the `Vec`).
