### ISSUE TITLE
[question] Is it possible to load a folder of assets into a single struct ?

### ISSUE THREAD

**Issue by VincentFoulon80** [a1phyr/assets_manager#4]
I started working on a multiple-file, folder-based Localization system.
In short, I want to be able to load an asset by specifying a directory, like having the `Loader` being able to load more resources than a single file.
Also, is there a way to list directories from an asset path ? In the same way, I have a folder for each supported languages, and I would like to load them without knowing their name beforehand.

**Edit:** it seems that the `Compound` trait might do what I was looking for.

**Comment by VincentFoulon80** [comment]
I'd like to suggest another feature : recursive asset loading

Consider having nested directories with the same kind of asset. It would be neat to be able to load all assets from our folder but also the subfolders and so on.
This will certainly lead us to specify in parameter a maximum depth to avoid trying to load too much data.

**Comment by a1phyr** [comment]
All your use cases for this should be fulfilled with the new directory APIs that will come in `0.5`
