### ISSUE TITLE
`No space left on device` when loading assets

### ISSUE THREAD

**Issue by zesterer** [a1phyr/assets_manager#5]
The original [Reddit error report](https://www.reddit.com/r/Veloren/comments/kp1z72/game_crashing_on_startup/) mentions that this error is produced when attempting to create an `AssetCache`.

The error, it seems, originates from [`Filesystem::new`](https://github.com/a1phyr/assets_manager/blob/master/src/source/filesystem.rs#L74).

I'm a little perplexed by this once because I don't see any reason for the code to write to the storage medium in a manner that would trigger such an error.

**Comment by a1phyr** [comment]
This error comes from `notify`.

This error can be throwed by [`inotify_add_watch`](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html) when `The user limit on the total number of inotify watches was reached or the kernel failed to allocate a needed resource`. To fix this, [increasing the watch limit](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached) should work.
