### ISSUE TITLE
Setting `windows_subsystem = "windows"` will cause resources to not load

### ISSUE THREAD

**Issue by kotx** [a1phyr/assets_manager#7]
I have this at the top of my `main.rs`:
```rs
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]
```

Therefore, in release builds, the resources will not load. There is no error, the data just seems to be empty.

This is not the case for release builds with the above line commented out.

**Comment by a1phyr** [comment]
Thanks for reporting the issue !

I do not have enough information to fix this, though.
- Does `#![windows_subsystem = "windows"]` do anything more than preventing the terminal to appear ?
- Do you have anything else that changes between debug and release mode ?
- And most important, what do you mean by "empty" ? Rust type system should ensure that you get either a valid value for your type or an error.

**Comment by kotx** [comment]
Oh, sorry, turns out `windows_subsystem` isn't the cause, I forgot to update this issue. I had an unsafe block in a `Loader` impl and I forgot about the lifetime of `content: std::borrow::Cow<[u8]>`. Whoops.
